//
//  Selections.swift
//  MovieNight
//
//  Created by Michael Guatambu Davis on 3/1/18.
//  Copyright © 2018 leme group. All rights reserved.
//

import Foundation

struct Selections {
    var yourGenres = [String]()
    var yourPeople = [String]()
    var yourFriendGenres = [String]()
    var yourFriendPeople = [String]()
    var aggregateGenreSelections = [String]()
    var aggregatePeopleSelections = [String]()
    var results = [String]()
    
    
    //in the YourResultsViewController in the prepare(for:segue) comment line i have the movie results object being passed to the movie results VC
    //example of complete object results:
    //selections:
    // .yougenres ["Action", "Comedy", "Horror"]
    // .youpeople ["name2", "name4", "name5"]
    // .yourFriendgenres ["Drama", "Science Fiction", "Adventure"]
    // .yourFriendPeople ["name2", "name5", "name3"]
    //however, with stub data this is appropriate, but the actual results will be the result of the network call that will be made using the URL generated by the comparison of the two users selections
    //the users selections comparison will:
    //look in the two genre arrays for any overlap
    //look in the two people arrays for any overlap
    //then it will spit out a flatmap array removing any overlapping duplicates and generate a MovieAPI URL for the network call for those overlapping strings
    //if there is no overlap between the users two selections, then it will spit out a flatmapped array of all the strings present
    //from here, the network call will be made with a MovieDB API "discover" query
    //case 1: using the overlapping strings as query parameters to query the MovieDB API using *** and/or *** query parameters to get all results including the overlapping user selections
    //case 2: an alert window will come up giving the users a warning that their selections produed no common results and they will be given the choice to proceed with a search that includes all their various input which could be quite a lot of results or to start over and try again for some overlap
    //the YourResultsTableViewController will then display the results of the above network call
    
    func resultsSynthesis() {
        for selection in selections.yourGenres {
            selections.aggregateGenreSelections.append(selection)
        }
        for selection in selections.yourFriendGenres {
            selections.aggregateGenreSelections.append(selection)
        }
        for selection in selections.yourPeople {
            selections.aggregatePeopleSelections.append(selection)
        }
        for selection in selections.yourFriendPeople {
            selections.aggregatePeopleSelections.append(selection)
        }
        
        print("\(selections.aggregateGenreSelections)\n\(selections.aggregatePeopleSelections)")
        
        let uniqueGenreResults = Array(Set(selections.aggregateGenreSelections))
        let uniquePeopleResults = Array(Set(selections.aggregatePeopleSelections))
        
        for result in uniqueGenreResults{
            selections.results.append(result)
        }
        for result in uniquePeopleResults {
            selections.results.append(result)
        }
        print("\(uniqueGenreResults)\n\(uniquePeopleResults)")
        
        print(selections.results)
    }
    
    
}


